name: Build all packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn setup
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
      # Unfortunately this crashes due to low memory on GitHub runners
      # - run: yarn test:types
      - run: yarn test
