name: Build all packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn setup
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test:types
      - run: yarn build
      - run: yarn test
