name: Build all packages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@rimbu'
      - run: yarn setup
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
      # Unfortunately this crashes due to low memory on GitHub runners
      # - run: yarn test:types
      - run: yarn test
