name: Publish release to NPM
on:
  release:
    types: [published]
jobs:
  build:
    if: '!github.event.release.prerelease'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@rimbu'
      - name: Checkout and pull branch
        run: git checkout "${GITHUB_REF:11}" && git pull
      - name: Check npm authentication
        run: npm whoami
      - run: yarn setup
      - run: yarn build
      - run: yarn test
      - run: yarn publish-all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
